[theme]
primaryColor = "#C9A84C"
backgroundColor = "#06070A"
secondaryBackgroundColor = "#11131A"
textColor = "#F1F1F4"
font = "sans serif"

[ui]
initialSidebarState = "expanded"

[server]
headless = true
